/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Omar Sebastián
 */
public class FrameInternoActualizacionesConsultasDemCivil extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfiActualizacionDemandaCivil
     */
    public FrameInternoActualizacionesConsultasDemCivil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneActCamDatosGenerales = new javax.swing.JTabbedPane();
        panelDatosGenerales = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        btnActualizarBusqueda = new javax.swing.JButton();
        comboBusqueda = new javax.swing.JComboBox<>();
        scrollDatosGenerales = new javax.swing.JScrollPane();
        panelInternoDatosGenerales = new javax.swing.JPanel();
        lblDomicilioTrabajador = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblNombreTrabajador = new javax.swing.JLabel();
        txtDomicilioCliente = new javax.swing.JTextField();
        txtDomicilioClienteAux = new javax.swing.JTextField();
        lblDatosPatron = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefonoAuxiliar = new javax.swing.JLabel();
        txtTelefonoAuxiliar = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblNumExpediente = new javax.swing.JLabel();
        txtIdDemandaCivil = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblPoblacion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        taDatosConflicto = new javax.swing.JTextArea();
        lblDomicilioAuxTrabajador = new javax.swing.JLabel();
        btnInsertarDatosGenerales = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        panelRelacionPruebas = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnInsertarRelacionPruebas = new javax.swing.JButton();
        btnActualizarRelacionPruebas = new javax.swing.JButton();
        btnBorrarRelacionPruebas = new javax.swing.JButton();
        panelControles = new javax.swing.JPanel();
        scrollControles = new javax.swing.JScrollPane();
        panelInternoControles = new javax.swing.JPanel();
        lblDespachoRemitidor = new javax.swing.JLabel();
        txtDespachoRemitidor = new javax.swing.JTextField();
        lblHonorarios = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taHonorarios = new javax.swing.JTextArea();
        lblGastos = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taGastos = new javax.swing.JTextArea();
        lblAsignacionInterna = new javax.swing.JLabel();
        txtAsignacionInterna = new javax.swing.JTextField();
        lblProveniencia = new javax.swing.JLabel();
        txtProveniencia = new javax.swing.JTextField();
        lblAsignadoA = new javax.swing.JLabel();
        lblDistribucion = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        taDistribucionHonorarios = new javax.swing.JTextArea();
        lblDistribucionHonorarios = new javax.swing.JLabel();
        lblNotasControl = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        taNotasControl = new javax.swing.JTextArea();
        lblFechaIngreso = new javax.swing.JLabel();
        lblFechaControlAdministrativo = new javax.swing.JLabel();
        lblFechaControlDocumental = new javax.swing.JLabel();
        dateChooserFechaIngreso = new com.toedter.calendar.JDateChooser();
        dateChooserFechaControlAdministrativo = new com.toedter.calendar.JDateChooser();
        dateChooserFechaControlDocumental = new com.toedter.calendar.JDateChooser();
        lblNumConsecutivo = new javax.swing.JLabel();
        txtNumConsecutivo = new javax.swing.JTextField();
        lblFechaRecepcionGestion = new javax.swing.JLabel();
        dateChooserFechaRecepcionGestion = new com.toedter.calendar.JDateChooser();
        comboAsigandoA = new javax.swing.JComboBox<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        listaAsignadoA = new javax.swing.JList<>();
        btnActualizarControles = new javax.swing.JButton();
        panelBoletaElaboracionEntrega = new javax.swing.JPanel();
        scrollBoletaElabEnt = new javax.swing.JScrollPane();
        panelInternoBoletaElaboracionEntrega = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblFechaElaboracion = new javax.swing.JLabel();
        dateChooserFechaElaboracion = new com.toedter.calendar.JDateChooser();
        lblFechaRemision = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        dateChooserFechaRemision = new com.toedter.calendar.JDateChooser();
        dateChooserFechaEntrega = new com.toedter.calendar.JDateChooser();
        btnActualizarFechas = new javax.swing.JButton();
        lblNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnInsertarPruebas = new javax.swing.JButton();
        btnActualizarPruebas = new javax.swing.JButton();
        btnBorrarPruebas = new javax.swing.JButton();
        btnBorrarPruebasPendientes = new javax.swing.JButton();
        btnActualizarPruebasPendientes = new javax.swing.JButton();
        btnInsertarPruebasPendientes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1350, 680));

        jTabbedPaneActCamDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneActCamDatosGenerales.setAutoscrolls(true);
        jTabbedPaneActCamDatosGenerales.setPreferredSize(new java.awt.Dimension(1000, 660));

        panelDatosGenerales.setBackground(new java.awt.Color(255, 204, 204));
        panelDatosGenerales.setAutoscrolls(true);
        panelDatosGenerales.setMinimumSize(new java.awt.Dimension(1000, 660));

        panelBusqueda.setBackground(new java.awt.Color(255, 51, 51));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel22.setBackground(new java.awt.Color(255, 51, 51));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Búsqueda de Demanda Laboral que desea actualizar");

        btnBusqueda.setText("Buscar");

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(jTable10);

        btnActualizarBusqueda.setText("Actualizar Info");

        comboBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBusqueda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addComponent(txtBusqueda)
                                .addGap(10, 10, 10)
                                .addComponent(btnBusqueda)))
                        .addGap(12, 12, 12)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnActualizarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel34)
                .addGap(6, 6, 6)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(comboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBusqueda)
                            .addComponent(btnBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelInternoDatosGenerales.setAutoscrolls(true);
        panelInternoDatosGenerales.setPreferredSize(new java.awt.Dimension(1000, 1420));

        lblDomicilioTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDomicilioTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDomicilioTrabajador.setText("Domicilio: ");

        lblNombreTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreTrabajador.setText("Nombre del Patrón/Cliente: ");

        lblDatosPatron.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDatosPatron.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDatosPatron.setText("Datos de la Consulta / Requerimientos / Defensa a Entablar");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefono.setText("Telefono: ");

        lblTelefonoAuxiliar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefonoAuxiliar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefonoAuxiliar.setText("Telefono Auxiliar: ");

        lblCelular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Celular: ");

        lblNumExpediente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumExpediente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumExpediente.setText("Número de Expediente:");

        lblCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCiudad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCiudad.setText("Ciudad: ");

        lblPoblacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPoblacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoblacion.setText("Población: ");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado: ");

        taDatosConflicto.setColumns(20);
        taDatosConflicto.setRows(5);
        jScrollPane8.setViewportView(taDatosConflicto);

        lblDomicilioAuxTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDomicilioAuxTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDomicilioAuxTrabajador.setText("Domicilio Auxiliar:  ");

        btnInsertarDatosGenerales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsertarDatosGenerales.setText("Insertar Datos");
        btnInsertarDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDatosGeneralesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoDatosGeneralesLayout = new javax.swing.GroupLayout(panelInternoDatosGenerales);
        panelInternoDatosGenerales.setLayout(panelInternoDatosGeneralesLayout);
        panelInternoDatosGeneralesLayout.setHorizontalGroup(
            panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(lblCiudad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCiudad)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPoblacion))
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(lblTelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(lblTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(txtTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(lblDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDomicilioAuxTrabajador)
                                            .addComponent(lblNombreTrabajador))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                                            .addComponent(txtDomicilioClienteAux)))))))
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdDemandaCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatosPatron)
                            .addComponent(btnInsertarDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInternoDatosGeneralesLayout.setVerticalGroup(
            panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdDemandaCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilioClienteAux, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDomicilioAuxTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblDatosPatron)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnInsertarDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        scrollDatosGenerales.setViewportView(panelInternoDatosGenerales);

        javax.swing.GroupLayout panelDatosGeneralesLayout = new javax.swing.GroupLayout(panelDatosGenerales);
        panelDatosGenerales.setLayout(panelDatosGeneralesLayout);
        panelDatosGeneralesLayout.setHorizontalGroup(
            panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDatosGenerales)
                .addContainerGap())
        );
        panelDatosGeneralesLayout.setVerticalGroup(
            panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(scrollDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPaneActCamDatosGenerales.addTab("Datos Generales", panelDatosGenerales);

        panelRelacionPruebas.setPreferredSize(new java.awt.Dimension(1000, 660));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane11.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Relación de Pruebas / Documentos / Testigos");

        btnInsertarRelacionPruebas.setText("Añadir Más Pruebas");

        btnActualizarRelacionPruebas.setText("Actualizar Pruebas");

        btnBorrarRelacionPruebas.setText("Borrar Pruebas");

        javax.swing.GroupLayout panelRelacionPruebasLayout = new javax.swing.GroupLayout(panelRelacionPruebas);
        panelRelacionPruebas.setLayout(panelRelacionPruebasLayout);
        panelRelacionPruebasLayout.setHorizontalGroup(
            panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(935, Short.MAX_VALUE))
                    .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        panelRelacionPruebasLayout.setVerticalGroup(
            panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                        .addComponent(btnInsertarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPaneActCamDatosGenerales.addTab("Relación de Pruebas", panelRelacionPruebas);

        panelControles.setPreferredSize(new java.awt.Dimension(1000, 660));

        panelInternoControles.setPreferredSize(new java.awt.Dimension(1000, 1840));

        lblDespachoRemitidor.setText("Despacho Remitidor: ");

        lblHonorarios.setText("Honorarios:");

        taHonorarios.setColumns(20);
        taHonorarios.setRows(5);
        jScrollPane6.setViewportView(taHonorarios);

        lblGastos.setText("Gastos: ");

        taGastos.setColumns(20);
        taGastos.setRows(5);
        jScrollPane7.setViewportView(taGastos);

        lblAsignacionInterna.setText("Asignación Interna: ");

        lblProveniencia.setText("Proveniencia:");

        lblAsignadoA.setText("Asignado a: ");

        lblDistribucion.setText("Distribución de");

        taDistribucionHonorarios.setColumns(20);
        taDistribucionHonorarios.setRows(5);
        jScrollPane14.setViewportView(taDistribucionHonorarios);

        lblDistribucionHonorarios.setText("Honorarios: ");

        lblNotasControl.setText("Notas de Control: ");

        taNotasControl.setColumns(20);
        taNotasControl.setRows(5);
        jScrollPane15.setViewportView(taNotasControl);

        lblFechaIngreso.setText("Fecha Ingreso: ");

        lblFechaControlAdministrativo.setText("Fecha Control Administrativo: ");

        lblFechaControlDocumental.setText("Fecha Control Documental: ");

        lblNumConsecutivo.setText("Número Consecutivo: ");

        lblFechaRecepcionGestion.setText("Fecha (Recibido para Gestión): ");

        comboAsigandoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listaAsignadoA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(listaAsignadoA);

        btnActualizarControles.setText("Actualizar Información de Controles");

        javax.swing.GroupLayout panelInternoControlesLayout = new javax.swing.GroupLayout(panelInternoControles);
        panelInternoControles.setLayout(panelInternoControlesLayout);
        panelInternoControlesLayout.setHorizontalGroup(
            panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarControles, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane15)
                        .addComponent(jScrollPane7)
                        .addComponent(txtDespachoRemitidor)
                        .addComponent(jScrollPane6)
                        .addGroup(panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAsignacionInterna)
                                .addComponent(lblProveniencia)
                                .addComponent(lblAsignadoA))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProveniencia)
                                .addComponent(txtAsignacionInterna)
                                .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                    .addComponent(comboAsigandoA, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDistribucion)
                                .addComponent(lblDistribucionHonorarios))
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane14))
                        .addComponent(lblNotasControl)
                        .addComponent(lblGastos)
                        .addComponent(lblHonorarios)
                        .addComponent(lblDespachoRemitidor)
                        .addGroup(panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                        .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFechaIngreso)
                                            .addComponent(lblFechaControlAdministrativo)
                                            .addComponent(lblFechaControlDocumental))
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoControlesLayout.createSequentialGroup()
                                        .addComponent(lblFechaRecepcionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                    .addComponent(lblNumConsecutivo)
                                    .addGap(87, 87, 87)))
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateChooserFechaRecepcionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumConsecutivo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateChooserFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateChooserFechaControlAdministrativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateChooserFechaControlDocumental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panelInternoControlesLayout.setVerticalGroup(
            panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDespachoRemitidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDespachoRemitidor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHonorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignacionInterna)
                    .addComponent(txtAsignacionInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveniencia)
                    .addComponent(txtProveniencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAsignadoA)
                        .addComponent(comboAsigandoA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoControlesLayout.createSequentialGroup()
                        .addComponent(lblDistribucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDistribucionHonorarios))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNotasControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInternoControlesLayout.createSequentialGroup()
                        .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFechaIngreso)
                                    .addComponent(dateChooserFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(lblFechaControlAdministrativo))
                            .addComponent(dateChooserFechaControlAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(lblFechaControlDocumental))
                    .addComponent(dateChooserFechaControlDocumental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumConsecutivo)
                    .addComponent(txtNumConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaRecepcionGestion)
                    .addComponent(dateChooserFechaRecepcionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnActualizarControles, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        scrollControles.setViewportView(panelInternoControles);

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollControles, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollControles, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPaneActCamDatosGenerales.addTab("Controles", panelControles);

        panelBoletaElaboracionEntrega.setPreferredSize(new java.awt.Dimension(1000, 660));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación de Pruebas Aportadas por el Cliente"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane19.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane19)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación a Tramitar por el despacho"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane20.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas Clave"));

        lblFechaElaboracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaElaboracion.setText("Fecha de Elaboración: ");

        lblFechaRemision.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaRemision.setText("Fecha de Remisión: ");

        lblFechaEntrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaEntrega.setText("Fecha de Entrega: ");

        btnActualizarFechas.setText("Actualizar Fechas y Notas");

        lblNotas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotas.setText("Notas: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNotas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaElaboracion)
                                    .addComponent(lblFechaRemision)
                                    .addComponent(lblFechaEntrega))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateChooserFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(dateChooserFechaRemision, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(dateChooserFechaElaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                                .addComponent(btnActualizarFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaElaboracion)
                            .addComponent(dateChooserFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaRemision)
                            .addComponent(dateChooserFechaRemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnActualizarFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaEntrega)
                    .addComponent(dateChooserFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(lblNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnInsertarPruebas.setText("Añadir Más Pruebas");

        btnActualizarPruebas.setText("Actualizar Pruebas");

        btnBorrarPruebas.setText("Borrar Prueba");

        btnBorrarPruebasPendientes.setText("Borrar Prueba");

        btnActualizarPruebasPendientes.setText("Actualizar Pruebas");

        btnInsertarPruebasPendientes.setText("Añadir Más Pruebas");

        javax.swing.GroupLayout panelInternoBoletaElaboracionEntregaLayout = new javax.swing.GroupLayout(panelInternoBoletaElaboracionEntrega);
        panelInternoBoletaElaboracionEntrega.setLayout(panelInternoBoletaElaboracionEntregaLayout);
        panelInternoBoletaElaboracionEntregaLayout.setHorizontalGroup(
            panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                        .addComponent(btnBorrarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                        .addComponent(btnBorrarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelInternoBoletaElaboracionEntregaLayout.setVerticalGroup(
            panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarPruebasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        scrollBoletaElabEnt.setViewportView(panelInternoBoletaElaboracionEntrega);

        javax.swing.GroupLayout panelBoletaElaboracionEntregaLayout = new javax.swing.GroupLayout(panelBoletaElaboracionEntrega);
        panelBoletaElaboracionEntrega.setLayout(panelBoletaElaboracionEntregaLayout);
        panelBoletaElaboracionEntregaLayout.setHorizontalGroup(
            panelBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBoletaElabEnt)
        );
        panelBoletaElaboracionEntregaLayout.setVerticalGroup(
            panelBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBoletaElabEnt, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPaneActCamDatosGenerales.addTab("Boleta de Entrega", panelBoletaElaboracionEntrega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneActCamDatosGenerales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneActCamDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDatosGeneralesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarDatosGeneralesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBusqueda;
    private javax.swing.JButton btnActualizarControles;
    private javax.swing.JButton btnActualizarFechas;
    private javax.swing.JButton btnActualizarPruebas;
    private javax.swing.JButton btnActualizarPruebasPendientes;
    private javax.swing.JButton btnActualizarRelacionPruebas;
    private javax.swing.JButton btnBorrarPruebas;
    private javax.swing.JButton btnBorrarPruebasPendientes;
    private javax.swing.JButton btnBorrarRelacionPruebas;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnInsertarDatosGenerales;
    private javax.swing.JButton btnInsertarPruebas;
    private javax.swing.JButton btnInsertarPruebasPendientes;
    private javax.swing.JButton btnInsertarRelacionPruebas;
    private javax.swing.JComboBox<String> comboAsigandoA;
    private javax.swing.JComboBox<String> comboBusqueda;
    private com.toedter.calendar.JDateChooser dateChooserFechaControlAdministrativo;
    private com.toedter.calendar.JDateChooser dateChooserFechaControlDocumental;
    private com.toedter.calendar.JDateChooser dateChooserFechaElaboracion;
    private com.toedter.calendar.JDateChooser dateChooserFechaEntrega;
    private com.toedter.calendar.JDateChooser dateChooserFechaIngreso;
    private com.toedter.calendar.JDateChooser dateChooserFechaRecepcionGestion;
    private com.toedter.calendar.JDateChooser dateChooserFechaRemision;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPaneActCamDatosGenerales;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAsignacionInterna;
    private javax.swing.JLabel lblAsignadoA;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDatosPatron;
    private javax.swing.JLabel lblDespachoRemitidor;
    private javax.swing.JLabel lblDistribucion;
    private javax.swing.JLabel lblDistribucionHonorarios;
    private javax.swing.JLabel lblDomicilioAuxTrabajador;
    private javax.swing.JLabel lblDomicilioTrabajador;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaControlAdministrativo;
    private javax.swing.JLabel lblFechaControlDocumental;
    private javax.swing.JLabel lblFechaElaboracion;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFechaRecepcionGestion;
    private javax.swing.JLabel lblFechaRemision;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblHonorarios;
    private javax.swing.JLabel lblNombreTrabajador;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblNotasControl;
    private javax.swing.JLabel lblNumConsecutivo;
    private javax.swing.JLabel lblNumExpediente;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblProveniencia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoAuxiliar;
    private javax.swing.JList<String> listaAsignadoA;
    private javax.swing.JPanel panelBoletaElaboracionEntrega;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelDatosGenerales;
    private javax.swing.JPanel panelInternoBoletaElaboracionEntrega;
    private javax.swing.JPanel panelInternoControles;
    private javax.swing.JPanel panelInternoDatosGenerales;
    private javax.swing.JPanel panelRelacionPruebas;
    private javax.swing.JScrollPane scrollBoletaElabEnt;
    private javax.swing.JScrollPane scrollControles;
    private javax.swing.JScrollPane scrollDatosGenerales;
    private javax.swing.JTextArea taDatosConflicto;
    private javax.swing.JTextArea taDistribucionHonorarios;
    private javax.swing.JTextArea taGastos;
    private javax.swing.JTextArea taHonorarios;
    private javax.swing.JTextArea taNotasControl;
    private javax.swing.JTextField txtAsignacionInterna;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDespachoRemitidor;
    private javax.swing.JTextField txtDomicilioCliente;
    private javax.swing.JTextField txtDomicilioClienteAux;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdDemandaCivil;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumConsecutivo;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtProveniencia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoAuxiliar;
    // End of variables declaration//GEN-END:variables
}
