/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Cesz
 */
public class FrameInternoServiciosPrestados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameInernoServiciosPrestados
     */
    public FrameInternoServiciosPrestados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResumenServicios = new javax.swing.JPanel();
        lblResumenServicios = new javax.swing.JLabel();
        nombreClienteResumenServicios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResumenServicios = new javax.swing.JTable();
        btnInfoGeneral = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        panelResumenServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResumenServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResumenServicios.setForeground(new java.awt.Color(51, 51, 51));
        lblResumenServicios.setText("Resumen de Servicios Prestados al cliente ");
        panelResumenServicios.add(lblResumenServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        nombreClienteResumenServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreClienteResumenServicios.setForeground(new java.awt.Color(51, 51, 51));
        nombreClienteResumenServicios.setText("[Nombre_Ciente]");
        panelResumenServicios.add(nombreClienteResumenServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 10, -1, -1));

        jTableResumenServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Servicio", "Número Consecutivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResumenServicios);

        panelResumenServicios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 140));

        btnInfoGeneral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInfoGeneral.setText("Ir a información General de Servicio");
        btnInfoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGeneralActionPerformed(evt);
            }
        });
        panelResumenServicios.add(btnInfoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelResumenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelResumenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfoGeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResumenServicios;
    private javax.swing.JLabel lblResumenServicios;
    private javax.swing.JLabel nombreClienteResumenServicios;
    private javax.swing.JPanel panelResumenServicios;
    // End of variables declaration//GEN-END:variables
}
