/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author Cesz
 */
public class FrameInternoOpcionesDemanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameInternoOpcionesDemanda
     */
    public FrameInternoOpcionesDemanda() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbDemCivil = new javax.swing.JRadioButton();
        rbDemLab = new javax.swing.JRadioButton();
        cbTipoDem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        buttonGroup1.add(rbDemCivil);
        rbDemCivil.setText("Demanda Civil");
        rbDemCivil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbDemCivilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbDemCivilFocusLost(evt);
            }
        });
        rbDemCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDemCivilMouseClicked(evt);
            }
        });
        rbDemCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDemCivilActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDemLab);
        rbDemLab.setText("Demanda Laboral");
        rbDemLab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbDemLabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbDemLabFocusLost(evt);
            }
        });
        rbDemLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDemLabMouseClicked(evt);
            }
        });
        rbDemLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDemLabActionPerformed(evt);
            }
        });

        cbTipoDem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opción" }));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(cbTipoDem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbDemCivil)
                        .addGap(18, 18, 18)
                        .addComponent(rbDemLab)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDemCivil)
                    .addComponent(rbDemLab))
                .addGap(18, 18, 18)
                .addComponent(cbTipoDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDemCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDemCivilActionPerformed
   
        
    }//GEN-LAST:event_rbDemCivilActionPerformed

    private void rbDemCivilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbDemCivilFocusGained
        
    }//GEN-LAST:event_rbDemCivilFocusGained

    private void rbDemCivilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbDemCivilFocusLost
        
    }//GEN-LAST:event_rbDemCivilFocusLost

    private void rbDemLabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbDemLabFocusGained
        
    }//GEN-LAST:event_rbDemLabFocusGained

    private void rbDemLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDemLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDemLabActionPerformed

    private void rbDemLabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbDemLabFocusLost
       
    }//GEN-LAST:event_rbDemLabFocusLost

    private void rbDemCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDemCivilMouseClicked
        rbDemLab.setSelected(false);
        rbDemCivil.setSelected(true);
        cbTipoDem.removeAllItems();
        cbTipoDem.addItem("Mercantil");
        cbTipoDem.addItem("Familiar");
        cbTipoDem.addItem("Civil");
        cbTipoDem.addItem("Penal");
        cbTipoDem.addItem("Fiscal");
    }//GEN-LAST:event_rbDemCivilMouseClicked

    private void rbDemLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDemLabMouseClicked
        rbDemLab.setSelected(true);
        rbDemCivil.setSelected(false);
        cbTipoDem.removeAllItems();
        cbTipoDem.addItem("Actor");
        cbTipoDem.addItem("Demandado");
    }//GEN-LAST:event_rbDemLabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameInternoAltaDemandaLaboral fadl=new FrameInternoAltaDemandaLaboral();
        JDesktopPane desk=getDesktopPane();
        Dimension desktopSize = desk.getSize();
        Dimension jInternalFrameSize = fadl.getSize();
        fadl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);      
        desk.add(fadl);
        fadl.show();
        
          this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipoDem;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton rbDemCivil;
    private javax.swing.JRadioButton rbDemLab;
    // End of variables declaration//GEN-END:variables
}
