/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Omar Sebastián
 */
public class FrameInternoAltaDemandaPatronal extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfiAltaDemandaPatronal
     */
    public FrameInternoAltaDemandaPatronal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAltaDemPatronal = new javax.swing.JTabbedPane();
        panelDatosGenerales = new javax.swing.JPanel();
        scrollDatosGenerales = new javax.swing.JScrollPane();
        panelInternoDatosGenerales = new javax.swing.JPanel();
        lblDomicilioTrabajador = new javax.swing.JLabel();
        txtNombreTrabajador = new javax.swing.JTextField();
        lblNombreTrabajador = new javax.swing.JLabel();
        txtDomicilioTrabajador = new javax.swing.JTextField();
        txtDomicilioTrabajadorAux = new javax.swing.JTextField();
        lblDatosConflicto = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefonoAuxiliar = new javax.swing.JLabel();
        txtTelefonoAuxiliar = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblNumExpediente = new javax.swing.JLabel();
        txtIdDemandaLaboral = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblPoblacion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        taDatosConflicto = new javax.swing.JTextArea();
        lblDomicilioAuxTrabajador = new javax.swing.JLabel();
        lblJunta = new javax.swing.JLabel();
        txtJunta = new javax.swing.JTextField();
        lblExpediente = new javax.swing.JLabel();
        txtExpediente = new javax.swing.JTextField();
        lblAudienciaInicial = new javax.swing.JLabel();
        btnInsertarDatosGenerales = new javax.swing.JButton();
        panelAccPrestHech = new javax.swing.JPanel();
        scrollAccPrestHech = new javax.swing.JScrollPane();
        panelInternoAccPrestHech = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taHechosDemanda = new javax.swing.JTextArea();
        btnInsertarDefensaEnderezar = new javax.swing.JButton();
        btnInsertarPrestacionesReclamar = new javax.swing.JButton();
        btnInsertarHechosDatosDemanda = new javax.swing.JButton();
        panelRelacionPruebas = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsertarRelacionPruebas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelControles = new javax.swing.JPanel();
        scrollControles = new javax.swing.JScrollPane();
        panelInternoControles = new javax.swing.JPanel();
        lblDespachoRemitidor = new javax.swing.JLabel();
        txtDespachoRemitidor = new javax.swing.JTextField();
        lblHonorarios = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taHonorarios = new javax.swing.JTextArea();
        lblGastos = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taGastos = new javax.swing.JTextArea();
        lblAsignacionInterna = new javax.swing.JLabel();
        txtAsignacionInterna = new javax.swing.JTextField();
        lblProveniencia = new javax.swing.JLabel();
        txtProveniencia = new javax.swing.JTextField();
        lblAsignadoA = new javax.swing.JLabel();
        lblDistribucion = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        taDistribucionHonorarios = new javax.swing.JTextArea();
        lblDistribucionHonorarios = new javax.swing.JLabel();
        lblNotasControl = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        taNotasControl = new javax.swing.JTextArea();
        lblFechaIngreso = new javax.swing.JLabel();
        lblFechaControlAdministrativo = new javax.swing.JLabel();
        lblFechaControlDocumental = new javax.swing.JLabel();
        lblNumConsecutivo = new javax.swing.JLabel();
        txtNumConsecutivo = new javax.swing.JTextField();
        lblFechaRecepcionGestion = new javax.swing.JLabel();
        comboAsigandoA = new javax.swing.JComboBox<>();
        jScrollPane16 = new javax.swing.JScrollPane();
        listaAsignadoA = new javax.swing.JList<>();
        btnInsertarControles = new javax.swing.JButton();
        panelBoletaElaboracionEntrega = new javax.swing.JPanel();
        scrollBoletaEntElab = new javax.swing.JScrollPane();
        panelInternoBoletaElaboracionEntrega = new javax.swing.JPanel();
        lblFechaElaboracion = new javax.swing.JLabel();
        lblFechaRemision = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblNumeroExpediente = new javax.swing.JLabel();
        txtNumeroExpediente = new javax.swing.JTextField();
        btnInsertarBoletaElabEntrega = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1350, 680));

        jTabbedPaneAltaDemPatronal.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneAltaDemPatronal.setAutoscrolls(true);
        jTabbedPaneAltaDemPatronal.setPreferredSize(new java.awt.Dimension(1000, 660));

        panelDatosGenerales.setAutoscrolls(true);
        panelDatosGenerales.setMinimumSize(new java.awt.Dimension(1000, 660));

        panelInternoDatosGenerales.setAutoscrolls(true);
        panelInternoDatosGenerales.setPreferredSize(new java.awt.Dimension(1000, 1550));

        lblDomicilioTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDomicilioTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDomicilioTrabajador.setText("Domicilio del Trabajador: ");

        lblNombreTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreTrabajador.setText("Nombre del Trabajador: ");

        lblDatosConflicto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDatosConflicto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDatosConflicto.setText("Datos del Conflicto: ");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefono.setText("Telefono: ");

        lblTelefonoAuxiliar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefonoAuxiliar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefonoAuxiliar.setText("Telefono Auxiliar: ");

        lblCelular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Celular: ");

        lblNumExpediente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumExpediente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumExpediente.setText("Número de Expediente:");

        lblCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCiudad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCiudad.setText("Ciudad: ");

        lblPoblacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPoblacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoblacion.setText("Población: ");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado: ");

        taDatosConflicto.setColumns(20);
        taDatosConflicto.setRows(5);
        jScrollPane8.setViewportView(taDatosConflicto);

        lblDomicilioAuxTrabajador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDomicilioAuxTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDomicilioAuxTrabajador.setText("Domicilio Auxiliar del Trabajador: ");

        lblJunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJunta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJunta.setText("Junta: ");

        lblExpediente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExpediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExpediente.setText("Expediente: ");

        lblAudienciaInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAudienciaInicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAudienciaInicial.setText("Audiencia Inicial: ");

        btnInsertarDatosGenerales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsertarDatosGenerales.setText("Insertar Datos");
        btnInsertarDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDatosGeneralesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoDatosGeneralesLayout = new javax.swing.GroupLayout(panelInternoDatosGenerales);
        panelInternoDatosGenerales.setLayout(panelInternoDatosGeneralesLayout);
        panelInternoDatosGeneralesLayout.setHorizontalGroup(
            panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdDemandaLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                            .addComponent(lblCiudad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCiudad)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblPoblacion))
                                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                            .addComponent(lblTelefono)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(lblTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                            .addComponent(txtTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                            .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblEstado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addComponent(lblDomicilioAuxTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDomicilioTrabajadorAux))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInternoDatosGeneralesLayout.createSequentialGroup()
                                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDatosConflicto)
                                .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblExpediente)
                                        .addComponent(lblJunta)
                                        .addComponent(lblAudienciaInicial))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJunta, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnInsertarDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        panelInternoDatosGeneralesLayout.setVerticalGroup(
            panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdDemandaLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoDatosGeneralesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtDomicilioTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDomicilioTrabajadorAux, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDomicilioAuxTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJunta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJunta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInternoDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAudienciaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblDatosConflicto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnInsertarDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        scrollDatosGenerales.setViewportView(panelInternoDatosGenerales);

        javax.swing.GroupLayout panelDatosGeneralesLayout = new javax.swing.GroupLayout(panelDatosGenerales);
        panelDatosGenerales.setLayout(panelDatosGeneralesLayout);
        panelDatosGeneralesLayout.setHorizontalGroup(
            panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        panelDatosGeneralesLayout.setVerticalGroup(
            panelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosGeneralesLayout.createSequentialGroup()
                .addComponent(scrollDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jTabbedPaneAltaDemPatronal.addTab("Datos Generales", panelDatosGenerales);

        panelAccPrestHech.setPreferredSize(new java.awt.Dimension(1000, 660));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Defensa a Enderezar"));

        jLabel1.setText("NOTA:     Aquí va un file chooser");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguimiento de las prestaciones reclamadas"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguimiento de los Hechos de la demanda"));

        taHechosDemanda.setColumns(20);
        taHechosDemanda.setRows(5);
        jScrollPane2.setViewportView(taHechosDemanda);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnInsertarDefensaEnderezar.setText("Añadir Datos");

        btnInsertarPrestacionesReclamar.setText("Añadir Datos");

        btnInsertarHechosDatosDemanda.setText("Añadir Datos");

        javax.swing.GroupLayout panelInternoAccPrestHechLayout = new javax.swing.GroupLayout(panelInternoAccPrestHech);
        panelInternoAccPrestHech.setLayout(panelInternoAccPrestHechLayout);
        panelInternoAccPrestHechLayout.setHorizontalGroup(
            panelInternoAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoAccPrestHechLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInternoAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsertarHechosDatosDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInsertarDefensaEnderezar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarPrestacionesReclamar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panelInternoAccPrestHechLayout.setVerticalGroup(
            panelInternoAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoAccPrestHechLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertarDefensaEnderezar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertarPrestacionesReclamar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertarHechosDatosDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        scrollAccPrestHech.setViewportView(panelInternoAccPrestHech);

        javax.swing.GroupLayout panelAccPrestHechLayout = new javax.swing.GroupLayout(panelAccPrestHech);
        panelAccPrestHech.setLayout(panelAccPrestHechLayout);
        panelAccPrestHechLayout.setHorizontalGroup(
            panelAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollAccPrestHech, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        panelAccPrestHechLayout.setVerticalGroup(
            panelAccPrestHechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollAccPrestHech, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPaneAltaDemPatronal.addTab("Acciones a Enderezar, Prestaciones Reclamadas y Hechos", panelAccPrestHech);

        panelRelacionPruebas.setPreferredSize(new java.awt.Dimension(1000, 660));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane11.setViewportView(jTable1);

        btnInsertarRelacionPruebas.setText("Añadir Pruebas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Relación de Pruebas / Documentos / Testigos");

        javax.swing.GroupLayout panelRelacionPruebasLayout = new javax.swing.GroupLayout(panelRelacionPruebas);
        panelRelacionPruebas.setLayout(panelRelacionPruebasLayout);
        panelRelacionPruebasLayout.setHorizontalGroup(
            panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnInsertarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelRelacionPruebasLayout.setVerticalGroup(
            panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionPruebasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelRelacionPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarRelacionPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPaneAltaDemPatronal.addTab("Relación de Pruebas", panelRelacionPruebas);

        panelControles.setPreferredSize(new java.awt.Dimension(1000, 660));

        panelInternoControles.setPreferredSize(new java.awt.Dimension(1000, 1800));

        lblDespachoRemitidor.setText("Despacho Remitidor: ");

        lblHonorarios.setText("Honorarios:");

        taHonorarios.setColumns(20);
        taHonorarios.setRows(5);
        jScrollPane6.setViewportView(taHonorarios);

        lblGastos.setText("Gastos: ");

        taGastos.setColumns(20);
        taGastos.setRows(5);
        jScrollPane7.setViewportView(taGastos);

        lblAsignacionInterna.setText("Asignación Interna: ");

        lblProveniencia.setText("Proveniencia:");

        lblAsignadoA.setText("Asignado a: ");

        lblDistribucion.setText("Distribución de");

        taDistribucionHonorarios.setColumns(20);
        taDistribucionHonorarios.setRows(5);
        jScrollPane13.setViewportView(taDistribucionHonorarios);

        lblDistribucionHonorarios.setText("Honorarios: ");

        lblNotasControl.setText("Notas de Control: ");

        taNotasControl.setColumns(20);
        taNotasControl.setRows(5);
        jScrollPane14.setViewportView(taNotasControl);

        lblFechaIngreso.setText("Fecha Ingreso: ");

        lblFechaControlAdministrativo.setText("Fecha Control Administrativo: ");

        lblFechaControlDocumental.setText("Fecha Control Documental: ");

        lblNumConsecutivo.setText("Número Consecutivo: ");

        lblFechaRecepcionGestion.setText("Fecha (Recibido para Gestión): ");

        comboAsigandoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listaAsignadoA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(listaAsignadoA);

        btnInsertarControles.setText("Añadir Información de Controles");

        javax.swing.GroupLayout panelInternoControlesLayout = new javax.swing.GroupLayout(panelInternoControles);
        panelInternoControles.setLayout(panelInternoControlesLayout);
        panelInternoControlesLayout.setHorizontalGroup(
            panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertarControles, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane14)
                        .addComponent(jScrollPane7)
                        .addComponent(txtDespachoRemitidor)
                        .addComponent(jScrollPane6)
                        .addGroup(panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAsignacionInterna)
                                .addComponent(lblProveniencia)
                                .addComponent(lblAsignadoA))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProveniencia)
                                .addComponent(txtAsignacionInterna)
                                .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                    .addComponent(comboAsigandoA, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDistribucion)
                                .addComponent(lblDistribucionHonorarios))
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane13))
                        .addGroup(panelInternoControlesLayout.createSequentialGroup()
                            .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNotasControl)
                                .addComponent(lblGastos)
                                .addComponent(lblHonorarios)
                                .addComponent(lblDespachoRemitidor)
                                .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                    .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFechaIngreso)
                                                    .addComponent(lblFechaControlAdministrativo)
                                                    .addComponent(lblFechaControlDocumental))
                                                .addGap(48, 48, 48))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoControlesLayout.createSequentialGroup()
                                                .addComponent(lblFechaRecepcionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)))
                                        .addGroup(panelInternoControlesLayout.createSequentialGroup()
                                            .addComponent(lblNumConsecutivo)
                                            .addGap(87, 87, 87)))
                                    .addComponent(txtNumConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panelInternoControlesLayout.setVerticalGroup(
            panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoControlesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDespachoRemitidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDespachoRemitidor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHonorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignacionInterna)
                    .addComponent(txtAsignacionInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveniencia)
                    .addComponent(txtProveniencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAsignadoA)
                        .addComponent(comboAsigandoA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoControlesLayout.createSequentialGroup()
                        .addComponent(lblDistribucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDistribucionHonorarios))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNotasControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblFechaIngreso)
                .addGap(50, 50, 50)
                .addComponent(lblFechaControlAdministrativo)
                .addGap(50, 50, 50)
                .addComponent(lblFechaControlDocumental)
                .addGap(46, 46, 46)
                .addGroup(panelInternoControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumConsecutivo)
                    .addComponent(txtNumConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblFechaRecepcionGestion)
                .addGap(46, 46, 46)
                .addComponent(btnInsertarControles, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        scrollControles.setViewportView(panelInternoControles);

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollControles, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollControles, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPaneAltaDemPatronal.addTab("Controles", panelControles);

        panelBoletaElaboracionEntrega.setPreferredSize(new java.awt.Dimension(1000, 660));

        lblFechaElaboracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaElaboracion.setText("Fecha de Elaboración: ");

        lblFechaRemision.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaRemision.setText("Fecha de Remisión: ");

        lblFechaEntrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechaEntrega.setText("Fecha de Entrega: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación de Pruebas Remitidas"));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane17.setViewportView(jList3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane17)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación de Pruebas Pendientes"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane18.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblNumeroExpediente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumeroExpediente.setText("Número de Expediente: ");

        btnInsertarBoletaElabEntrega.setText("Añadir Información");

        javax.swing.GroupLayout panelInternoBoletaElaboracionEntregaLayout = new javax.swing.GroupLayout(panelInternoBoletaElaboracionEntrega);
        panelInternoBoletaElaboracionEntrega.setLayout(panelInternoBoletaElaboracionEntregaLayout);
        panelInternoBoletaElaboracionEntregaLayout.setHorizontalGroup(
            panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertarBoletaElabEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaEntrega)
                            .addComponent(lblFechaRemision)
                            .addComponent(lblFechaElaboracion)))
                    .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                        .addComponent(lblNumeroExpediente)
                        .addGap(46, 46, 46)
                        .addComponent(txtNumeroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelInternoBoletaElaboracionEntregaLayout.setVerticalGroup(
            panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoBoletaElaboracionEntregaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblFechaElaboracion)
                .addGap(39, 39, 39)
                .addComponent(lblFechaRemision)
                .addGap(41, 41, 41)
                .addComponent(lblFechaEntrega)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panelInternoBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroExpediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnInsertarBoletaElabEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        scrollBoletaEntElab.setViewportView(panelInternoBoletaElaboracionEntrega);

        javax.swing.GroupLayout panelBoletaElaboracionEntregaLayout = new javax.swing.GroupLayout(panelBoletaElaboracionEntrega);
        panelBoletaElaboracionEntrega.setLayout(panelBoletaElaboracionEntregaLayout);
        panelBoletaElaboracionEntregaLayout.setHorizontalGroup(
            panelBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBoletaEntElab)
        );
        panelBoletaElaboracionEntregaLayout.setVerticalGroup(
            panelBoletaElaboracionEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBoletaEntElab, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        jTabbedPaneAltaDemPatronal.addTab("Boleta de Elaboración y de Entrega", panelBoletaElaboracionEntrega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAltaDemPatronal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneAltaDemPatronal, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDatosGeneralesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarDatosGeneralesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertarBoletaElabEntrega;
    private javax.swing.JButton btnInsertarControles;
    private javax.swing.JButton btnInsertarDatosGenerales;
    private javax.swing.JButton btnInsertarDefensaEnderezar;
    private javax.swing.JButton btnInsertarHechosDatosDemanda;
    private javax.swing.JButton btnInsertarPrestacionesReclamar;
    private javax.swing.JButton btnInsertarRelacionPruebas;
    private javax.swing.JComboBox<String> comboAsigandoA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPaneAltaDemPatronal;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblAsignacionInterna;
    private javax.swing.JLabel lblAsignadoA;
    private javax.swing.JLabel lblAudienciaInicial;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDatosConflicto;
    private javax.swing.JLabel lblDespachoRemitidor;
    private javax.swing.JLabel lblDistribucion;
    private javax.swing.JLabel lblDistribucionHonorarios;
    private javax.swing.JLabel lblDomicilioAuxTrabajador;
    private javax.swing.JLabel lblDomicilioTrabajador;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblExpediente;
    private javax.swing.JLabel lblFechaControlAdministrativo;
    private javax.swing.JLabel lblFechaControlDocumental;
    private javax.swing.JLabel lblFechaElaboracion;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFechaRecepcionGestion;
    private javax.swing.JLabel lblFechaRemision;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblHonorarios;
    private javax.swing.JLabel lblJunta;
    private javax.swing.JLabel lblNombreTrabajador;
    private javax.swing.JLabel lblNotasControl;
    private javax.swing.JLabel lblNumConsecutivo;
    private javax.swing.JLabel lblNumExpediente;
    private javax.swing.JLabel lblNumeroExpediente;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblProveniencia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoAuxiliar;
    private javax.swing.JList<String> listaAsignadoA;
    private javax.swing.JPanel panelAccPrestHech;
    private javax.swing.JPanel panelBoletaElaboracionEntrega;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelDatosGenerales;
    private javax.swing.JPanel panelInternoAccPrestHech;
    private javax.swing.JPanel panelInternoBoletaElaboracionEntrega;
    private javax.swing.JPanel panelInternoControles;
    private javax.swing.JPanel panelInternoDatosGenerales;
    private javax.swing.JPanel panelRelacionPruebas;
    private javax.swing.JScrollPane scrollAccPrestHech;
    private javax.swing.JScrollPane scrollBoletaEntElab;
    private javax.swing.JScrollPane scrollControles;
    private javax.swing.JScrollPane scrollDatosGenerales;
    private javax.swing.JTextArea taDatosConflicto;
    private javax.swing.JTextArea taDistribucionHonorarios;
    private javax.swing.JTextArea taGastos;
    private javax.swing.JTextArea taHechosDemanda;
    private javax.swing.JTextArea taHonorarios;
    private javax.swing.JTextArea taNotasControl;
    private javax.swing.JTextField txtAsignacionInterna;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDespachoRemitidor;
    private javax.swing.JTextField txtDomicilioTrabajador;
    private javax.swing.JTextField txtDomicilioTrabajadorAux;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtExpediente;
    private javax.swing.JTextField txtIdDemandaLaboral;
    private javax.swing.JTextField txtJunta;
    private javax.swing.JTextField txtNombreTrabajador;
    private javax.swing.JTextField txtNumConsecutivo;
    private javax.swing.JTextField txtNumeroExpediente;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtProveniencia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoAuxiliar;
    // End of variables declaration//GEN-END:variables
}
