/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Cesz
 */
public class jfiUsuarios extends javax.swing.JInternalFrame {
    String  nombre,
            nombreUsuario,
            contraseña,
            telefono,
            celular,
            correo,
            domicilio,
            ciudad,
            estado,
            tipoUsuario,
            status
            ;
    /**
     * Creates new form jfiUsuarios
     */
    public jfiUsuarios() {
        initComponents();
        nombre = tfNombre.getText();
        nombreUsuario = tfNombreUsuario.getText();
        contraseña = tfContraseña.getText();
        telefono = tfTelefono.getText();
        celular = tfCelular.getText();
        correo = tfCorreo.getText();
        domicilio = tfDomicilio.getText();
        ciudad = tfCiudad.getText();
        estado = tfEstado.getText();
        tipoUsuario = tfTipoUsuario.getText();
        status = tfStatus.getText();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        tfNombreUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        tfDomicilio = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        tfCiudad = new javax.swing.JTextField();
        lblTipoUsuario = new javax.swing.JLabel();
        tfTipoUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jpBotones = new javax.swing.JPanel();
        btnAgregarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jpUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuarios"
            }
        ));
        jtUsuarios.setAlignmentX(0.0F);
        jtUsuarios.setAlignmentY(0.0F);
        jScrollPane1.setViewportView(jtUsuarios);
        if (jtUsuarios.getColumnModel().getColumnCount() > 0) {
            jtUsuarios.getColumnModel().getColumn(0).setResizable(false);
        }

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre:");

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreUsuario.setText("Nombre de Usuario:");

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(51, 51, 51));
        lblContraseña.setText("Contraseña: ");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(51, 51, 51));
        lblTelefono.setText("Teléfono:");

        lblCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(51, 51, 51));
        lblCelular.setText("Celular:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(51, 51, 51));
        lblCorreo.setText("Correo:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Estado");

        lblDomicilio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDomicilio.setForeground(new java.awt.Color(51, 51, 51));
        lblDomicilio.setText("Domicilio:");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblStatus.setText("STATUS:");

        lblCiudad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(51, 51, 51));
        lblCiudad.setText("Ciudad: ");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(102, 102, 102));

        tfStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNombreUsuario.setForeground(new java.awt.Color(102, 102, 102));

        tfContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfContraseña.setForeground(new java.awt.Color(102, 102, 102));

        tfCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoUsuario.setText("Tipo de Usuario:");

        tfTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setText("INFORMACIÓN GENERAL DE USUARIO");

        jpBotones.setBackground(new java.awt.Color(255, 255, 255));
        jpBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        btnAgregarUsuario.setText("Agregar Usuario");

        btnModificarUsuario.setText("Modificar Usuario");

        btnEliminarUsuario.setText("Eliminar Usuario");

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpUsuariosLayout = new javax.swing.GroupLayout(jpUsuarios);
        jpUsuarios.setLayout(jpUsuariosLayout);
        jpUsuariosLayout.setHorizontalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuariosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblStatus)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfStatus))
                                .addGroup(jpUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblUsuario)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfEstado))
                                .addGroup(jpUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblCiudad)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfCiudad))
                                .addGroup(jpUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblTipoUsuario)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfTipoUsuario))
                                .addGroup(jpUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblDomicilio)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpUsuariosLayout.createSequentialGroup()
                                .addComponent(lblCorreo)
                                .addGap(18, 18, 18)
                                .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpUsuariosLayout.createSequentialGroup()
                                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpUsuariosLayout.createSequentialGroup()
                                            .addComponent(lblNombreUsuario)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfNombreUsuario))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpUsuariosLayout.createSequentialGroup()
                                            .addComponent(lblNombre)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jpUsuariosLayout.createSequentialGroup()
                                            .addComponent(lblCelular)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCelular))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpUsuariosLayout.createSequentialGroup()
                                            .addComponent(lblTelefono)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfTelefono))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpUsuariosLayout.createSequentialGroup()
                                            .addComponent(lblContraseña)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jpUsuariosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpUsuariosLayout.setVerticalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jpUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUsuariosLayout.createSequentialGroup()
                        .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre)
                            .addGroup(jpUsuariosLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreUsuario)
                            .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContraseña)
                            .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpUsuariosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio)
                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCiudad)
                    .addComponent(tfCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(tfTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCiudad;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreUsuario;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
