/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;

/**
 *
 * @author Omar Sebastián
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuAltaDemLab = new javax.swing.JMenuItem();
        menuActualizacionesDemLab = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        menuAltDemPatronal = new javax.swing.JMenuItem();
        menuAcualizacionesDemPatronal = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu11 = new javax.swing.JMenu();
        menuAltDemCivil = new javax.swing.JMenuItem();
        menuActualizacionesDemCivil = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miReportesClientes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Despacho Garnica & Garibay Asociados");

        jPanel1.setBackground(new java.awt.Color(141, 170, 158));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1322, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu2.setText("Usuarios");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu7.setText("Clientes");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        jMenu3.setText("Demandas");

        jMenu9.setText("Demandas Laborales");

        menuAltaDemLab.setText("Alta de Demanda");
        menuAltaDemLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAltaDemLabMouseClicked(evt);
            }
        });
        menuAltaDemLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaDemLabActionPerformed(evt);
            }
        });
        jMenu9.add(menuAltaDemLab);

        menuActualizacionesDemLab.setText("Actualizaciones y Consultas");
        menuActualizacionesDemLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuActualizacionesDemLabMouseClicked(evt);
            }
        });
        menuActualizacionesDemLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizacionesDemLabActionPerformed(evt);
            }
        });
        jMenu9.add(menuActualizacionesDemLab);

        jMenu3.add(jMenu9);
        jMenu3.add(jSeparator1);

        jMenu10.setText("Demandas Patronales");

        menuAltDemPatronal.setText("Alta de Demanda");
        menuAltDemPatronal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltDemPatronalActionPerformed(evt);
            }
        });
        jMenu10.add(menuAltDemPatronal);

        menuAcualizacionesDemPatronal.setText("Actualizaciones y Consultas");
        menuAcualizacionesDemPatronal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcualizacionesDemPatronalActionPerformed(evt);
            }
        });
        jMenu10.add(menuAcualizacionesDemPatronal);

        jMenu3.add(jMenu10);
        jMenu3.add(jSeparator2);

        jMenu11.setText("Demandas Civiles");

        menuAltDemCivil.setText("Alta de Demanda");
        menuAltDemCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltDemCivilActionPerformed(evt);
            }
        });
        jMenu11.add(menuAltDemCivil);

        menuActualizacionesDemCivil.setText("Actualizaciones y Consultas");
        menuActualizacionesDemCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizacionesDemCivilActionPerformed(evt);
            }
        });
        jMenu11.add(menuActualizacionesDemCivil);

        jMenu3.add(jMenu11);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Reportes");

        miReportesClientes.setText("Clientes");
        miReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportesClientesActionPerformed(evt);
            }
        });
        jMenu4.add(miReportesClientes);
        jMenu4.add(jSeparator3);

        jMenuItem1.setText("Asignación de Casos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator4);

        jMenuItem15.setText("Estado Procesal de Casos");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);
        jMenu4.add(jSeparator5);

        jMenuBar2.add(jMenu4);

        jMenu8.setText("Finanzas");
        jMenuBar2.add(jMenu8);

        jMenu6.setText("Agenda");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        jMenu5.setText("Acerca de");

        jMenuItem16.setText("Información General");
        jMenu5.add(jMenuItem16);

        jMenuItem17.setText("Ayuda");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAltaDemLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaDemLabActionPerformed
        // TODO add your handling code here:
        FrameInternoAltaDemandaLaboral jadl = new FrameInternoAltaDemandaLaboral();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jadl.getSize();
        jadl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);
        this.jDesktopPane1.add(jadl);
        jadl.show();
    }//GEN-LAST:event_menuAltaDemLabActionPerformed

    private void menuAltDemPatronalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltDemPatronalActionPerformed
        // TODO add your handling code here:
        FrameInternoAltaDemandaPatronal jadp = new FrameInternoAltaDemandaPatronal();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jadp.getSize();
        jadp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);        
        this.jDesktopPane1.add(jadp);
        jadp.show();       
    }//GEN-LAST:event_menuAltDemPatronalActionPerformed

    private void menuAltDemCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltDemCivilActionPerformed
        // TODO add your handling code here:
        FrameInternoAltaDemandaCivil jadc = new FrameInternoAltaDemandaCivil();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jadc.getSize();
        jadc.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);        
        this.jDesktopPane1.add(jadc);
        jadc.show();        
    }//GEN-LAST:event_menuAltDemCivilActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void menuAltaDemLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAltaDemLabMouseClicked
        // TODO add your handling code here:
        FrameInternoAltaDemandaLaboral jadl = new FrameInternoAltaDemandaLaboral();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jadl.getSize();
        jadl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);        
        this.jDesktopPane1.add(jadl);
        jadl.show();
    }//GEN-LAST:event_menuAltaDemLabMouseClicked

    private void menuActualizacionesDemLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuActualizacionesDemLabMouseClicked
        // TODO add your handling code here:
        FrameInternoActualizacionesConsultasDemLaboral judl = new FrameInternoActualizacionesConsultasDemLaboral();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = judl.getSize();
        judl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);              
        this.jDesktopPane1.add(judl);
        judl.show();
    }//GEN-LAST:event_menuActualizacionesDemLabMouseClicked

    private void menuActualizacionesDemLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizacionesDemLabActionPerformed
        // TODO add your handling code here:
        FrameInternoActualizacionesConsultasDemLaboral judl = new FrameInternoActualizacionesConsultasDemLaboral();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = judl.getSize();
        judl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);              
        this.jDesktopPane1.add(judl);
        judl.show();
    }//GEN-LAST:event_menuActualizacionesDemLabActionPerformed

    private void menuActualizacionesDemCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizacionesDemCivilActionPerformed
        // TODO add your handling code here:
        FrameInternoActualizacionesConsultasDemCivil judc = new FrameInternoActualizacionesConsultasDemCivil();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = judc.getSize();
        judc.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);              
        this.jDesktopPane1.add(judc);
        judc.show();
    }//GEN-LAST:event_menuActualizacionesDemCivilActionPerformed

    private void menuAcualizacionesDemPatronalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcualizacionesDemPatronalActionPerformed
        // TODO add your handling code here:
        FrameInternoActualizacionesConsultasDemPatronal judp = new FrameInternoActualizacionesConsultasDemPatronal();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = judp.getSize();
        judp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);              
        this.jDesktopPane1.add(judp);
        judp.show();        
    }//GEN-LAST:event_menuAcualizacionesDemPatronalActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        FrameInternoClientes fic = new FrameInternoClientes();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = fic.getSize();
        fic.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);

        jDesktopPane1.add(fic);
        fic.show();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        FrameInternoAgenda jadl = new FrameInternoAgenda();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jadl.getSize();
        jadl.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);

        jDesktopPane1.add(jadl);
        jadl.show();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        FrameInternoAgenda jfiA = new FrameInternoAgenda();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jfiA.getSize();
        jfiA.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);

        jDesktopPane1.add(jfiA);
        jfiA.show();
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        jfiUsuarios ju = new jfiUsuarios();
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = ju.getSize();
        ju.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 2);

        jDesktopPane1.add(ju);
        ju.show();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void miReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportesClientesActionPerformed

    }//GEN-LAST:event_miReportesClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrameInternoAsignacionCasos jfiAC = new FrameInternoAsignacionCasos();
        jDesktopPane1.add(jfiAC);
        jfiAC.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuActualizacionesDemCivil;
    private javax.swing.JMenuItem menuActualizacionesDemLab;
    private javax.swing.JMenuItem menuAcualizacionesDemPatronal;
    private javax.swing.JMenuItem menuAltDemCivil;
    private javax.swing.JMenuItem menuAltDemPatronal;
    private javax.swing.JMenuItem menuAltaDemLab;
    private javax.swing.JMenuItem miReportesClientes;
    // End of variables declaration//GEN-END:variables
}
